const assert=require('node:assert/strict');
const fs=require('node:fs');
module.exports=async page=>{
  const doc=()=>page.evaluate(()=>FZI.MathIllustration.editor.engine.toJSON());
  const move=async(x,y)=>{const p=await page.evaluate(p=>FZI.MathIllustration.editor.transform().mathToScreen(p),{x,y});await page.mouse.move(p.x,p.y);};
  const click=async(x,y)=>{await move(x,y);await page.mouse.down();await page.mouse.up();};
  const reset=()=>page.evaluate(()=>FZI.MathIllustration.editor.loadDocument({objects:[],presentation:{bounds:{xMin:-5,xMax:5,yMin:-3,yMax:3},showGrid:true}}));
  await reset(); await require('./browser-tool-menu.cjs').choose(page,'[data-tool="triangle"]');
  for(const p of [[-2,-1],[0,-1],[-1,1]]) await click(...p);
  let polygon=(await doc()).objects[0]; assert.equal(polygon.type,'polygon');assert.equal(polygon.vertices.length,3);
  assert.deepEqual(polygon.vertices,[{x:-2,y:-1},{x:0,y:-1},{x:-1,y:1}]);
  assert.equal(await page.evaluate(()=>FZI.MathIllustration.editor.history.entries.length),1);
  await page.locator('#undoBtn').click();assert.equal((await doc()).objects.length,0);await page.locator('#redoBtn').click();
  await require('./browser-tool-menu.cjs').choose(page,'[data-tool="select"]');
  await move(-1,0);await page.mouse.down();await move(0,1);await page.mouse.up();
  const translated=(await doc()).objects[0];assert.deepEqual(translated.vertices,polygon.vertices.map(p=>({x:p.x+1,y:p.y+1})));
  assert.equal(await page.locator('.fzi-polygon-vertex').count(),3);
  const handle=await page.locator('.fzi-polygon-vertex[data-vertex="0"]').boundingBox();
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await move(-2,0);
  assert.equal(await page.locator('[data-vertex="0"][data-edit="x"]').inputValue(),'-2');
  await page.mouse.up();assert.equal((await doc()).objects[0].vertices[0].x,-2);
  const changed=await doc();await page.locator('#undoBtn').click();assert.deepEqual((await doc()).objects[0].vertices,translated.vertices);await page.locator('#redoBtn').click();assert.deepEqual(await doc(),changed);
  await page.locator('[data-label-selection]').click();const label=await page.locator('.object-label').boundingBox();
  await page.mouse.move(label.x+label.width/2,label.y+label.height/2);await page.mouse.down();await page.mouse.move(label.x+label.width/2+20,label.y+label.height/2-10);await page.mouse.up();
  assert.ok((await doc()).objects[0].labelOffsetX>0);
  const download=page.waitForEvent('download');await require('./browser-tool-menu.cjs').action(page,'#exportSvgBtn');const svg=fs.readFileSync(await(await download).path(),'utf8');assert.match(svg,/<polygon /);assert.doesNotMatch(svg,/fzi-polygon-vertex|NaN|Infinity/);
  const saved=await doc();await page.locator('#saveBtn').click();await page.reload();assert.deepEqual(await doc(),saved);
  await page.locator('#fileInput').setInputFiles({name:'polygon.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await page.waitForFunction(()=>document.getElementById('status').textContent==='Illustratie geladen.');assert.deepEqual(await doc(),saved);
  await reset();await require('./browser-tool-menu.cjs').choose(page,'[data-tool="polygon"]');for(const p of [[-2,-1],[1,-1],[1,1],[-2,1]])await click(...p);
  assert.equal((await doc()).objects.length,0);await page.keyboard.press('Enter');assert.equal((await doc()).objects[0].vertices.length,4);
  await reset();await require('./browser-tool-menu.cjs').choose(page,'[data-tool="polygon"]');for(const p of [[-2,-1],[1,-1],[1,1],[-2,1],[-2,-1]])await click(...p);assert.equal((await doc()).objects[0].vertices.length,4);
  await reset();await require('./browser-tool-menu.cjs').choose(page,'[data-tool="polygon"]');await click(-2,-1);await click(1,-1);await page.keyboard.press('Backspace');assert.equal(await page.evaluate(()=>FZI.MathIllustration.editor.interaction.vertices.length),1);await page.keyboard.press('Escape');assert.equal((await doc()).objects.length,0);assert.equal(await page.evaluate(()=>FZI.MathIllustration.editor.history.canUndo),false);
  await reset();await require('./browser-tool-menu.cjs').choose(page,'[data-tool="polygon"]');for(const p of [[-2,-1],[1,1],[-2,1],[1,-1]])await click(...p);await page.keyboard.press('Enter');assert.equal((await doc()).objects.length,0);await page.keyboard.press('Escape');assert.equal(await page.locator('[data-drawing-preview]').count(),0);
  await page.evaluate(()=>localStorage.removeItem(FZI.MathIllustration.DraftStore.key));
  return {triangle:'passed',polygonEnterAndClosure:'passed',rigidDrag:'passed',vertexInspectorUndoRedo:'passed',labelDrag:'passed',SVGExport:'passed',saveReloadImport:'passed',BackspaceEscape:'passed',invalidShape:'passed'};
};
