const assert=require('node:assert/strict'),fs=require('node:fs');
module.exports=async page=>{
  const doc=()=>page.evaluate(()=>FZI.MathIllustration.editor.engine.toJSON());
  const selected=()=>page.evaluate(()=>FZI.MathIllustration.editor.selectedIds);
  const move=async p=>{const q=await page.evaluate(p=>FZI.MathIllustration.editor.transform().mathToScreen(p),p);await page.mouse.move(q.x,q.y);};
  await page.evaluate(()=>{const a=FZI.MathIllustration.editor;a.setTool('select');a.loadDocument({meta:{title:'Lagen',description:''},objects:[{id:'a',type:'point',x:0,y:0},{id:'b',type:'point',x:0,y:0},{id:'c',type:'line',x1:-2,y1:1,x2:2,y2:1}],presentation:{showGrid:false,bounds:{xMin:-4,xMax:4,yMin:-3,yMax:3}}});});
  const initial=await doc();await page.locator('[data-layer-new-name]').fill('Voorgrond');await page.locator('[data-layer-add]').click();let d=await doc(),top=d.layers[1].id,base=d.layers[0].id;assert.equal(d.version,5);assert.equal(d.layers.length,2);assert.deepEqual(d.objects,initial.objects);
  await page.locator('[data-select-object="a"]').click();await page.locator('[data-layer-assign]').selectOption(top);assert.deepEqual((await doc()).layers[1].members,['a']);await move({x:0,y:0});await page.mouse.down();await page.mouse.up();assert.deepEqual(await selected(),['a']);
  const paint=()=>page.locator('#canvas [data-object-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.objectId));assert.deepEqual(await paint(),['b','c','a']);
  await page.locator(`[data-layer-backward="${top}"]`).click();assert.deepEqual(await paint(),['a','b','c']);await move({x:0,y:0});await page.mouse.down();await page.mouse.up();assert.deepEqual(await selected(),['b']);await page.locator('#undoBtn').click();assert.deepEqual(await paint(),['b','c','a']);await page.locator('#redoBtn').click();assert.deepEqual(await paint(),['a','b','c']);await page.locator(`[data-layer-forward="${top}"]`).click();
  await page.locator(`[data-layer-name="${top}"]`).fill('Hulplijnen');await page.locator(`[data-layer-name="${top}"]`).press('Tab');assert.equal((await doc()).layers[1].name,'Hulplijnen');
  await page.locator(`[data-layer-visibility="${top}"]`).click();assert.deepEqual(await paint(),['b','c']);assert.equal((await doc()).objects.find(o=>o.id==='a').visible,true);await move({x:0,y:0});await page.mouse.down();await page.mouse.up();assert.deepEqual(await selected(),['b']);assert.ok(!(await page.evaluate(()=>FZI.MathIllustration.SnapService.candidates(FZI.MathIllustration.editor.engine))).some(c=>c.ids.includes('a')));
  await page.locator(`[data-layer-visibility="${top}"]`).click();assert.equal((await doc()).objects.find(o=>o.id==='a').visible,true);
  // Groups move as a unit between layers and remain locked together.
  await page.locator('[data-select-object="a"]').click();await page.locator('[data-select-object="b"]').click({modifiers:['Shift']});const beforeRefusal=await doc();await page.locator('[data-group-selection]').click();assert.deepEqual(await doc(),beforeRefusal);assert.match(await page.locator('#status').textContent(),/dezelfde laag/);
  await page.locator('[data-layer-assign]').selectOption(top);await page.locator('[data-group-selection]').click();assert.equal((await doc()).groups.length,1);await page.locator('[data-layer-assign]').selectOption(base);assert.ok((await doc()).layers[0].members.includes('a'));assert.ok((await doc()).layers[0].members.includes('b'));
  await page.locator('[data-object-lock="b"]').click();await move({x:0,y:0});const locked=await doc();await page.mouse.down();await move({x:1,y:1});await page.mouse.up();assert.deepEqual(await doc(),locked);await page.locator('[data-object-lock="b"]').click();
  // Hidden layer suppresses handles/source picking but does not break linked geometry.
  await page.evaluate(base=>{const a=FZI.MathIllustration.editor,m=a.engine.construct('midpoint',[{objectId:'a'},{objectId:'c',part:'end'}])[0];a.engine.assignLayer([m.id],a.engine.model.layers.find(l=>l.id!==base).id);a.layerProbe=m.id;a.invalidate();},base);
  await page.locator(`[data-layer-visibility="${base}"]`).click();assert.equal(await page.locator('.fzi-line-endpoint').count(),0);await page.evaluate(()=>{const a=FZI.MathIllustration.editor;a.changeDocument(()=>a.engine.update('c',{x2:4}));});assert.equal(await page.evaluate(()=>FZI.MathIllustration.editor.engine.get(FZI.MathIllustration.editor.layerProbe).x),2);assert.equal(await page.evaluate(()=>FZI.MathIllustration.editor.engine.get('c').visible),true);
  const saved=await doc();await page.locator('#saveBtn').click();await page.reload();assert.deepEqual(await doc(),saved);assert.equal(await page.locator('#canvas [data-object-id="a"]').count(),0);
  const svgDownload=page.waitForEvent('download');await page.locator('#exportSvgBtn').click();const svg=fs.readFileSync(await(await svgDownload).path(),'utf8');assert.doesNotMatch(svg,/data-object-id="a"|data-object-id="b"|data-object-id="c"|data-selection-highlight|NaN/);assert.match(svg,/data-object-id="point-/);
  const jsonDownload=page.waitForEvent('download');await page.locator('#exportJsonBtn').click();const exported=JSON.parse(fs.readFileSync(await(await jsonDownload).path(),'utf8'));assert.deepEqual(exported,saved);
  await page.evaluate(()=>FZI.MathIllustration.editor.newDocument());await page.locator('#fileInput').setInputFiles({name:'layers.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await page.waitForFunction(()=>FZI.MathIllustration.editor.engine.model.layers.length===2);assert.deepEqual(await doc(),saved);await page.locator('#undoBtn').click();assert.equal((await doc()).layers,undefined);await page.locator('#redoBtn').click();assert.deepEqual(await doc(),saved);
  // Layer edits cancel live group drag, retaining only one presentation history step.
  await page.locator(`[data-layer-visibility="${base}"]`).click();await page.locator('[data-select-object="a"]').click();const original=await doc();await move({x:0,y:0});await page.mouse.down();await move({x:1,y:-1});await page.evaluate(base=>{const a=FZI.MathIllustration.editor;a.changeDocument(()=>a.execute('layer.setVisibility',{id:base,value:false}));},base);await page.mouse.up();assert.deepEqual((await doc()).objects,original.objects);assert.equal(await page.evaluate(()=>FZI.MathIllustration.editor.interaction),null);
  await page.locator('#undoBtn').click();assert.deepEqual(await doc(),original);await page.locator(`[data-layer-delete="${top}"]`).click();assert.equal((await doc()).layers.length,1);assert.equal((await doc()).objects.length,4);await page.locator('#undoBtn').click();assert.deepEqual(await doc(),original);
  // Restricted layers are readonly and visibility is enforced by direct queries too.
  const {fixture}=require('./permission-fixtures.cjs'),options=fixture();options.initialDocument=saved;options.policy.parameters={};options.policy.initialObjectRules={a:{translate:true},b:{translate:true},c:{translate:true}};
  await page.evaluate(options=>{layerRuntime=FZI.MathIllustration.RuntimeSession.create(options);FZI.MathIllustration.bootstrapRestrictedEditor({runtimeSession:layerRuntime.session});},options);assert.equal(await page.locator('[data-layer-add]').count(),0);assert.equal(await page.locator('[data-layer-name]').count(),0);assert.equal(await page.locator('#canvas [data-object-id="a"]').count(),0);const restrictedBefore=await page.evaluate(()=>layerRuntime.owner.inspect());assert.equal(await page.evaluate(()=>layerRuntime.session.getObjectCapabilities('a').display),false);assert.equal(await page.evaluate(()=>layerRuntime.session.canExecute(layerRuntime.session.createCommand('layer.setVisibility',{id:layerRuntime.owner.inspect().document.layers[0].id,value:true})).allowed),false);assert.deepEqual(await page.evaluate(()=>layerRuntime.owner.inspect()),restrictedBefore);
  await page.evaluate(()=>{localStorage.removeItem(FZI.MathIllustration.DraftStore.key);FZI.MathIllustration.bootstrapEditor({restoreDraft:false});});
  return {createRenameAssign:'passed',paintHitOrder:'passed',orderUndoRedo:'passed',visibilityAndSnapping:'passed',groupAtomicityLocks:'passed',hiddenSourcesLinkedUpdate:'passed',saveReloadJSONSVG:'passed',importHistory:'passed',liveDragCancellation:'passed',deleteMergeHistory:'passed',restrictedRuntime:'passed'};
};
