// Optional real-browser smoke test: requires playwright and an installed Edge.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const server = http.createServer((req, res) => {
  const file = path.resolve(root, '.' + decodeURIComponent(req.url.split('?')[0]));
  if (!file.startsWith(root + path.sep)) { res.writeHead(403).end(); return; }
  fs.readFile(file, (error, data) => {
    if (error) { res.writeHead(404).end(); return; }
    res.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html');
    res.end(data);
  });
});
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    await page.route('https://fonts.googleapis.com/**', route => route.abort());
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/editor.html`);
    const before = await page.evaluate(() => FZI.MathIllustration.activeEngine.renderer.scale());
    const rect = await page.locator('#canvasWrap').boundingBox();
    await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
    await page.mouse.wheel(0, -100);
    await page.waitForFunction(value => FZI.MathIllustration.activeEngine.renderer.scale() > value, before);
    const result = await page.evaluate(() => {
      const e = FZI.MathIllustration.activeEngine, wrap = document.getElementById('canvasWrap'), rect = wrap.getBoundingClientRect();
      const wheel = deltaY => wrap.dispatchEvent(new WheelEvent('wheel', { bubbles: true, cancelable: true, deltaY, clientX: rect.x + rect.width / 2, clientY: rect.y + rect.height / 2 }));
      for (let i = 0; i < 30; i++) wheel(-100);
      const maxScale = e.renderer.scale(), step = e.renderer.axisStep, bounds = JSON.stringify(e.renderer.bounds);
      wheel(-100); const blocked = bounds === JSON.stringify(e.renderer.bounds);
      wheel(100); const outScale = e.renderer.scale();
      e.renderer.showGrid = true;
      for (let i = 0; i < 250; i++) wheel(100);
      const svg = e.renderSVG();
      return { maxScale, step, blocked, outScale, finite: !/NaN|Infinity/.test(svg), lines: (svg.match(/<line /g) || []).length };
    });
    assert.ok(Math.abs(result.maxScale - 700) < 1e-8); assert.equal(result.step, .1);
    assert.ok(result.blocked); assert.ok(result.outScale < 700); assert.ok(result.finite); assert.ok(result.lines < 1000);
    // Reset and verify ordinary authoring still works with all feature scripts loaded.
    await page.locator('#resetViewBtn').click();
    await require('./browser-tool-menu.cjs').choose(page,'[data-tool="point"]');
    await page.locator('#canvasWrap').click({ position: { x: 200, y: 200 } });
    assert.equal(await page.evaluate(() => FZI.MathIllustration.activeEngine.model.objects.length), 1);
    const legacy = fs.readFileSync(path.join(__dirname, 'fixtures', 'legacy-v1.json'));
    page.once('dialog',dialog=>{assert.equal(dialog.type(),'confirm');dialog.accept();});
    await page.locator('#fileInput').setInputFiles({ name: 'legacy.json', mimeType: 'application/json', buffer: legacy });
    await page.waitForFunction(() => document.getElementById('status').textContent === 'Illustratie geladen.');
    assert.equal(await page.evaluate(() => FZI.MathIllustration.activeEngine.get('A').name), 'Alpha');
    await page.locator('[data-view-select="axes"]').click();
    await page.locator('[data-axis-setting="showXAxis"]').click();
    await page.locator('[data-axis-setting="showGrid"]').click();
    await page.locator('[data-view-select="axes"]').click();
    await page.locator('summary').filter({ hasText: /^Illustratie$/ }).click();
    await page.locator('#titleInput').fill('Opgeslagen test');
    const labelPositions = () => page.evaluate(() => Array.from(document.querySelectorAll('#canvas .object-label'), n => [n.dataset.labelId, n.getAttribute('x'), n.getAttribute('y')]));
    const labels = await labelPositions();
    const saved = await page.evaluate(() => FZI.MathIllustration.activeEngine.toJSON());
    await page.locator('#saveBtn').click();
    await page.reload();
    await page.waitForFunction(() => document.getElementById('status').textContent === 'Opgeslagen concept geladen.');
    assert.deepEqual(await page.evaluate(() => FZI.MathIllustration.activeEngine.toJSON()), saved);
    assert.deepEqual(await labelPositions(), labels);
    const exportEvent = page.waitForEvent('download');
    await require('./browser-tool-menu.cjs').action(page,'#exportJsonBtn');
    const exported = await exportEvent;
    const exportedData = JSON.parse(fs.readFileSync(await exported.path(), 'utf8'));
    assert.deepEqual(exportedData, saved);
    await page.locator('#fileInput').setInputFiles({ name: 'roundtrip.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exportedData)) });
    await page.waitForFunction(() => document.getElementById('status').textContent === 'Illustratie geladen.');
    assert.deepEqual(await page.evaluate(() => FZI.MathIllustration.activeEngine.toJSON()), saved);
    assert.deepEqual(await labelPositions(), labels);
    const rejected = page.waitForEvent('dialog');
    await page.locator('#fileInput').setInputFiles({ name: 'duplicate.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ meta: { title: 'bad' }, objects: [{ id: 'x', type: 'point' }, { id: 'x', type: 'point' }] })) });
    const alert = await rejected; assert.match(alert.message(), /Object-id bestaat al/); await alert.accept();
    assert.deepEqual(await page.evaluate(() => FZI.MathIllustration.activeEngine.toJSON()), saved);
    const badDraft = '{bad';
    await page.evaluate(raw => localStorage.setItem(FZI.MathIllustration.DraftStore.key, raw), badDraft);
    await page.reload();
    assert.match(await page.locator('#status').textContent(), /gegevens zijn behouden/);
    assert.equal(await page.evaluate(() => localStorage.getItem(FZI.MathIllustration.DraftStore.key)), badDraft);
    assert.equal(await page.evaluate(() => FZI.MathIllustration.activeEngine.model.objects.length), 0);
    const confirmEvent = page.waitForEvent('dialog');
    const newClick = require('./browser-tool-menu.cjs').action(page,'#newBtn');
    const confirm = await confirmEvent; await confirm.accept(); await newClick;
    assert.equal(await page.evaluate(() => localStorage.getItem(FZI.MathIllustration.DraftStore.key)), null);
    await page.reload();
    assert.equal(await page.evaluate(() => FZI.MathIllustration.activeEngine.model.objects.length), 0);
    const snapping = await require('./browser-snapping.cjs')(page);
    const lifecycle = await require('./browser-lifecycle.cjs')(page);
    const performance = await require('./browser-performance.cjs')(page, true);
    const selection = await require('./browser-selection.cjs')(page);
    const auditFinal = await require('./browser-audit-final.cjs')(page);
    const linear = await require('./browser-linear.cjs')(page);
    const assetCompat = await require('./browser-asset-compat.cjs')(page);
    const history = await require('./browser-history.cjs')(page);
    const inputs = await require('./browser-inputs.cjs')(page);
    const polygon = await require('./browser-polygon.cjs')(page);
    const styles = await require('./browser-styles.cjs')(page);
    const measurementsGroups = await require('./browser-measurements-groups.cjs')(page);
    const constructions = await require('./browser-constructions.cjs')(page);
    const areaMenu=await require('./browser-area-menu.cjs')(page);
    const rectangleSelection=await require('./browser-rectangle-selection.cjs')(page);
    const selectionPresentation=await require('./browser-selection-presentation.cjs')(page);
    const permissions=await require('./browser-permissions.cjs')(page);
    const importHistory=await require('./browser-import-history.cjs')(page);
    const persistentGroups=await require('./browser-persistent-groups.cjs')(page);
    const layers=await require('./browser-layers.cjs')(page);
    const constructionContract=await require('./browser-construction-contract.cjs')(page);
    const uiModernization=await require('./browser-ui-modernization.cjs')(page);
    const uiRefinements=await require('./browser-ui-refinements.cjs')(page);
    const inspectorFeedback=await require('./browser-inspector-feedback.cjs')(page);
    const axesGrid=await require('./browser-axes-grid.cjs')(page);
    const constructionHover=await require('./browser-construction-hover.cjs')(page);
    const fullCanvasAxes=await require('./browser-full-canvas-axes.cjs')(page);
    const splitTools=await require('./browser-split-tools.cjs')(page);
    const bisectorClip=await require('./browser-bisector-clip.cjs')(page);
    const linkedPaths=await require('./browser-linked-paths.cjs')(page);
    const semanticSequence=await require('./browser-semantic-sequence.cjs')(page);
    const canvasFullscreen=await require('./browser-canvas-fullscreen.cjs')(page);
    const linkedTangent=await require('./browser-linked-tangent.cjs')(page);
    const derivedCircle=await require('./browser-derived-circle.cjs')(page);
    const circleCircle=await require('./browser-circle-circle.cjs')(page);
    const lineCircle=await require('./browser-line-circle.cjs')(page);
    const lineIntersection=await require('./browser-line-intersection.cjs')(page);
    const postM5aUX=await require('./browser-post-m5a-ux.cjs')(page);
    const minimalObjectList=await require('./browser-minimal-object-list.cjs')(page);
    const unitsScale=await require('./browser-units-scale.cjs')(page);
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ browser: 'Edge', ...result, pointCreation: 'passed', legacyImport: 'passed', saveReload: 'passed', labelRoundtrip: 'passed', presentationRestore: 'passed', exportImport: 'passed', atomicFailedImport: 'passed', corruptDraftRetained: 'passed', explicitNew: 'passed', snapping, lifecycle, performance, selection, auditFinal, linear, assetCompat, history, inputs, polygon, styles, measurementsGroups, constructions, areaMenu, rectangleSelection, selectionPresentation, permissions, importHistory, persistentGroups, layers, constructionContract, uiModernization, uiRefinements, inspectorFeedback, axesGrid, constructionHover, fullCanvasAxes, splitTools, bisectorClip, minimalObjectList,canvasFullscreen,semanticSequence,linkedPaths, postM5aUX, lineIntersection, lineCircle, circleCircle, derivedCircle, linkedTangent, unitsScale, pageErrors: errors }));
  } finally { if (browser) await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
