const test=require('node:test'),assert=require('node:assert/strict');const {runtime,plain}=require('./helpers.cjs');
const base=()=>[{id:'a',type:'point',x:0,y:0},{id:'b',type:'point',x:4,y:0},{id:'p',type:'point',x:2,y:3},{id:'l',type:'line',x1:0,y1:0,x2:4,y2:0},{id:'c',type:'circle',cx:0,cy:0,r:1}];
test('linked constructions recompute transitively and survive roundtrip',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()});const m=e.construct('midpoint',[{objectId:'a'},{objectId:'b'}])[0];assert.equal(m.x,2);const n=e.construct('midpoint',[{objectId:m.id},{objectId:'b'}])[0];e.update('b',{x:8});assert.equal(e.get(m.id).x,4);assert.equal(e.get(n.id).x,6);assert.deepEqual(plain(new MI.Engine(e.toJSON()).toJSON()),plain(e.toJSON()));});
test('perpendicular parallel bisector and perpendicular bisector preserve invariants',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()});for(const kind of ['perpendicular','parallel']){const o=e.construct(kind,[{objectId:'l'},{objectId:'p'}])[0];assert.equal(o.type,'straight');assert.equal(o.x1,2);assert.equal(o.y1,3);assert.ok(kind==='parallel'?o.y2===o.y1:o.x2===o.x1);}const o=e.construct('perpendicularBisector',[{objectId:'a'},{objectId:'b'}])[0];assert.equal(o.x1,2);assert.equal(o.x2,2);const b=e.construct('bisector',[{objectId:'b'},{objectId:'a'},{objectId:'p'}])[0];assert.equal(b.type,'ray');assert.equal(b.x1,0);});
test('tangents are one on circle, two outside, invalid inside and recover',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()});const ts=e.construct('tangent',[{objectId:'c'},{objectId:'p'}]);assert.equal(ts.length,2);for(const t of ts){const dx=t.x2-t.x1,dy=t.y2-t.y1;assert.ok(Math.abs(t.x2*dx+t.y2*dy)<1e-8);}e.update('p',{x:0,y:0});assert.ok(ts.every(t=>e.get(t.id).constructionValid===false));e.update('p',{x:1,y:0});assert.ok(ts.every(t=>e.get(t.id).constructionValid));});
test('references and cycles reject atomically; source deletion cascades',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()});const m=e.construct('midpoint',[{objectId:'a'},{objectId:'b'}])[0];const before=plain(e.toJSON());assert.throws(()=>e.update(m.id,{construction:{kind:'midpoint',sources:[{objectId:m.id},{objectId:'b'}]}}));assert.deepEqual(plain(e.toJSON()),before);e.remove('a');assert.equal(e.get(m.id),null);assert.ok(e.get('b'));});

test('invalid geometry hides derived objects and removes them from snapping until recovery',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()});const t=e.construct('tangent',[{objectId:'c'},{objectId:'p'}])[0];e.update('p',{x:0,y:0});assert.equal(e.renderer.renderObject(e.get(t.id)),'');assert.ok(!MI.SnapService.candidates(e).some(c=>c.ids.includes(t.id)));e.update('p',{x:2,y:3});assert.ok(e.renderer.renderObject(e.get(t.id)));});
test('linked imports reject missing references and invalid kinds atomically',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()}),before=plain(e.toJSON());for(const kind of ['midpoint','constructor','__proto__']){const data=plain(before);data.objects.push({id:'bad',type:'point',x:0,y:0,construction:{kind,sources:[{objectId:'missing'},{objectId:'b'}]}});assert.throws(()=>e.load(data));assert.deepEqual(plain(e.toJSON()),before);}});
test('source exclusion also excludes every dependent snap candidate',()=>{const {MI}=runtime();const e=new MI.Engine({objects:base()});const m=e.construct('midpoint',[{objectId:'a'},{objectId:'b'}])[0];assert.ok(!MI.SnapService.candidates(e,'a').some(c=>c.ids.includes(m.id)));});
test('polygon edges and vertices are stable references after edits',()=>{const {MI}=runtime();const e=new MI.Engine({objects:[{id:'poly',type:'polygon',vertices:[{x:0,y:0},{x:4,y:0},{x:0,y:3}]},{id:'p',type:'point',x:1,y:1}]});const m=e.construct('midpoint',[{objectId:'poly',part:'vertex',index:0},{objectId:'poly',part:'vertex',index:1}])[0];const l=e.construct('parallel',[{objectId:'poly',part:'edge',index:0},{objectId:'p'}])[0];e.update('poly',{vertices:[{x:0,y:0},{x:4,y:2},{x:0,y:3}]});assert.equal(e.get(m.id).y,1);const o=e.get(l.id);assert.ok(Math.abs((o.y2-o.y1)/(o.x2-o.x1)-.5)<1e-9);});
