const test=require('node:test'),assert=require('node:assert/strict');
const {runtime,plain}=require('./helpers.cjs');
function setup(){const {MI}=runtime(),e=new MI.Engine({objects:[{id:'a',type:'point',x:0,y:0},{id:'b',type:'point',x:2,y:0},{id:'c',type:'circle',cx:0,cy:0,r:1},{id:'poly',type:'polygon',vertices:[{x:0,y:0},{x:2,y:0},{x:0,y:2}]}]});return {MI,e};}
test('M4a construction definitions and geometric source capabilities are explicit and immutable',()=>{const {MI,e}=setup(),d=MI.ConstructionService.contract('parallel');assert.deepEqual(plain(d.sourceRoles),['line','point']);assert.equal(d.resultType,'straight');assert.equal(Object.isFrozen(d.sourceRoles),true);const refs=MI.ConstructionService.referenceOptions(e.get('poly'));assert.equal(refs.point.length,3);assert.equal(refs.line.length,3);assert.equal(refs.figure.length,1);assert.deepEqual(plain(refs.line[0]),{objectId:'poly',part:'edge',index:0});assert.throws(()=>MI.ConstructionService.contract('__proto__'));});
test('M4a wrong source roles and meaningless part/index references reject atomically',()=>{const {e}=setup(),before=plain(e.toJSON()),counter=e.model._nextId;for(const [kind,sources] of [['midpoint',[{objectId:'a',part:'edge',index:0},{objectId:'b'}]],['area',[{objectId:'poly',part:'vertex',index:0}]],['parallel',[{objectId:'poly',part:'vertex',index:0},{objectId:'a'}]],['midpoint',[{objectId:'a',index:0},{objectId:'b'}]],['tangent',[{objectId:'c',part:'start'},{objectId:'a'}]]]){assert.throws(()=>e.construct(kind,sources));assert.deepEqual(plain(e.toJSON()),before);assert.equal(e.model._nextId,counter);}});
test('M4a indexed topology changes cannot silently retarget constructions',()=>{const {e}=setup(),m=e.construct('midpoint',[{objectId:'poly',part:'vertex',index:0},{objectId:'poly',part:'vertex',index:1}])[0],before=plain(e.toJSON());assert.throws(()=>e.update('poly',{vertices:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:2}]}),error=>error.code==='TOPOLOGY_REFERENCED');assert.deepEqual(plain(e.toJSON()),before);e.update('poly',{vertices:[{x:0,y:0},{x:4,y:0},{x:0,y:2}]});assert.equal(e.get(m.id).x,2);});
test('M4a whole-figure references permit valid topology changes without indexed identities',()=>{const {e}=setup(),area=e.construct('area',[{objectId:'poly'}])[0];e.update('poly',{vertices:[{x:0,y:0},{x:2,y:0},{x:2,y:2},{x:0,y:2}]});assert.equal(e.get(area.id).text,'Oppervlakte = 4');});
test('M4a invalid reasons are transient queries and recover along dependency chains',()=>{const {e}=setup(),t=e.construct('tangent',[{objectId:'c'},{objectId:'b'}])[0],child=e.construct('parallel',[{objectId:t.id},{objectId:'a'}])[0];e.update('b',{x:.5});assert.equal(e.getConstructionInfo(t.id).reasonCode,'POINT_INSIDE_CIRCLE');assert.equal(e.getConstructionInfo(child.id).reasonCode,'SOURCE_INVALID');assert.equal(e.getConstructionInfo(t.id).canDetach,false);assert.equal(e.get(t.id).constructionReason,undefined);e.update('b',{x:2});assert.equal(e.getConstructionInfo(t.id).reasonCode,'VALID');assert.equal(e.getConstructionInfo(child.id).reasonCode,'VALID');assert.equal(e.getConstructionInfo('missing'),null);});
test('M4a coincident points and zero radius have specific recoverable reasons',()=>{const {e}=setup(),p=e.construct('perpendicularBisector',[{objectId:'a'},{objectId:'b'}])[0],t=e.construct('tangent',[{objectId:'c'},{objectId:'b'}])[0];e.update('b',{x:0});assert.equal(e.getConstructionInfo(p.id).reasonCode,'COINCIDENT_POINTS');e.update('c',{r:0});assert.equal(e.getConstructionInfo(t.id).reasonCode,'ZERO_RADIUS');});
test('M4a author detach preserves identity geometry layers groups and downstream links',()=>{const {MI,e}=setup(),m=e.construct('midpoint',[{objectId:'a'},{objectId:'b'}])[0],child=e.construct('midpoint',[{objectId:m.id},{objectId:'b'}])[0],layer=e.createLayer('Constructies');e.group([m.id,child.id]);e.assignLayer([m.id,child.id],layer.id);const before=e.get(m.id),groups=plain(e.model.groups),layers=plain(e.model.layers),commands=MI.AuthorCommands(e);commands.execute(commands.createCommand('construction.detach',{ids:[m.id]}));assert.equal(e.get(m.id).construction,undefined);assert.equal(e.get(m.id).constructionValid,undefined);assert.equal(e.get(m.id).x,before.x);assert.equal(e.getConstructionInfo(m.id).mode,'free');assert.deepEqual(plain(e.model.groups),groups);assert.deepEqual(plain(e.model.layers),layers);e.update('a',{x:-4});assert.equal(e.get(m.id).x,before.x);e.update(m.id,{x:3});assert.equal(e.get(child.id).x,2.5);e.remove('a');assert.ok(e.get(m.id));});
test('M4a detach refuses invalid locked missing and mixed batch targets atomically',()=>{const {e}=setup();assert.equal(typeof e.detachConstructions,'function');const m=e.construct('midpoint',[{objectId:'a'},{objectId:'b'}])[0],t=e.construct('tangent',[{objectId:'c'},{objectId:'b'}])[0];e.update('b',{x:.5});let before=plain(e.toJSON());assert.throws(()=>e.detachConstructions([m.id,t.id]));assert.deepEqual(plain(e.toJSON()),before);e.update(m.id,{locked:true});before=plain(e.toJSON());for(const ids of [[m.id],['missing'],['a'],[m.id,m.id]]){assert.throws(()=>e.detachConstructions(ids));assert.deepEqual(plain(e.toJSON()),before);}});
test('M4a legacy reference extensions survive contract queries and roundtrip',()=>{const {MI,e}=setup(),m=e.construct('midpoint',[{objectId:'a',anchor:'point',hostTag:'keep'},{objectId:'b'}])[0],saved=plain(e.toJSON());assert.equal(e.getConstructionInfo(m.id).mode,'linked');assert.equal(e.getConstructionInfo(m.id).sources[0].objectId,'a');assert.deepEqual(plain(e.toJSON()),saved);assert.deepEqual(plain(new MI.Engine(saved).toJSON()),saved);});
test('M4a restricted detach is denied and inspection redacts unread references/dependents',()=>{const {MI}=runtime(),{fixture}=require('./permission-fixtures.cjs'),options=fixture();options.policy.initialObjectRules.A={read:false};const {session:s,owner}=MI.RuntimeSession.create(options),before=plain(owner.inspect());const info=s.engine.getConstructionInfo('M');assert.equal(info.canDetach,false);assert.equal(info.hasRestrictedSources,true);assert.ok(!info.sources.some(r=>r.objectId==='A'));assert.equal(s.engine.getConstructionInfo('A'),null);assert.throws(()=>s.engine.detachConstructions(['M']),error=>error.code==='MODE_DENIED');assert.throws(()=>s.execute(s.createCommand('construction.detach',{ids:['M']})),error=>error.code==='MODE_DENIED');assert.deepEqual(plain(owner.inspect()),before);});

test('M4a calculated fields refuse direct engine edits while presentation remains editable',()=>{const {e}=setup(),m=e.construct('midpoint',[{objectId:'a'},{objectId:'b'}])[0],area=e.construct('area',[{objectId:'c'}])[0],before=plain(e.toJSON());assert.throws(()=>e.update(m.id,{x:10}),error=>error.code==='COMPUTED_FIELD');assert.throws(()=>e.update(area.id,{text:'Fake area'}),error=>error.code==='COMPUTED_FIELD');assert.deepEqual(plain(e.toJSON()),before);e.update(m.id,{showLabel:true,labelOffsetX:1,style:{stroke:'#ff0000'}});assert.equal(e.get(m.id).labelOffsetX,1);});

test('M4a transient tangent branches retain identity through invalidity and recovery',()=>{const {e}=setup(),ts=e.construct('tangent',[{objectId:'c'},{objectId:'b'}]);assert.deepEqual(ts.map(t=>e.getConstructionInfo(t.id).branch),[0,1]);e.update('b',{x:.5});assert.deepEqual(ts.map(t=>e.getConstructionInfo(t.id).branch),[0,1]);e.update('b',{x:2});assert.deepEqual(ts.map(t=>e.getConstructionInfo(t.id).branch),[0,1]);});
test('M4a reference capabilities do not interpret unrelated legacy extension fields as topology',()=>{const {MI,e}=setup();const o=e.add({type:'text',x:0,y:0,text:'Legacy',vertices:{host:'not geometry'}});assert.deepEqual(plain(MI.ConstructionService.referenceOptions(o)),{point:[],line:[],circle:[],figure:[]});});
