const test=require('node:test'),assert=require('node:assert/strict');
const {runtime,plain}=require('./helpers.cjs');
const data=()=>({objects:[{id:'a',type:'point',x:0,y:0},{id:'b',type:'point',x:0,y:0},{id:'c',type:'point',x:2,y:0}]});
function setup(){const {MI}=runtime();return {MI,e:new MI.Engine(data())};}
test('M3c first named layer preserves geometry and legacy paint order and creates base membership',()=>{const {e}=setup(),before=plain(e.model.objects),svg=e.renderSVG();const layer=e.createLayer('Voorgrond');assert.equal(e.model.layers.length,2);assert.equal(layer.name,'Voorgrond');assert.deepEqual(plain(e.model.layers[0].members),['a','b','c']);assert.deepEqual(plain(e.model.objects),before);assert.equal(e.renderSVG(),svg);assert.equal(e.toJSON().version,5);assert.equal(e.toJSON().layerSchema,1);});
test('M3c paint hit and SVG order use the same layer ordering',()=>{const {e}=setup(),g=e.createLayer('Top');e.assignLayer(['a'],g.id);assert.equal(e.selectAt(0,0).object.id,'a');let svg=e.renderSVG();assert.ok(svg.indexOf('data-object-id="b"')<svg.indexOf('data-object-id="a"'));e.reorderLayers(e.model.layers.map(l=>l.id).reverse());assert.equal(e.selectAt(0,0).object.id,'b');svg=e.renderSVG();assert.ok(svg.indexOf('data-object-id="a"')<svg.indexOf('data-object-id="b"'));});
test('M3c hidden layers gate selection snapping and standalone SVG without changing object visibility',()=>{const {MI,e}=setup(),g=e.createLayer('Top');e.assignLayer(['a'],g.id);e.setLayerVisibility(g.id,false);assert.equal(e.get('a').visible,true);assert.equal(e.selectAt(0,0).object.id,'b');assert.ok(!MI.SnapService.candidates(e).some(c=>c.ids.includes('a')));assert.doesNotMatch(new MI.SvgRenderer().render(e.model),/data-object-id="a"/);e.setLayerVisibility(g.id,true);assert.equal(e.selectAt(0,0).object.id,'a');});
test('M3c grouped members cannot split across layers or create cross-layer groups',()=>{const {e}=setup();e.group(['a','b']);const l=e.createLayer('Top'),before=plain(e.toJSON());assert.throws(()=>e.assignLayer(['a'],l.id));assert.deepEqual(plain(e.toJSON()),before);e.assignLayer(['a','b'],l.id);assert.throws(()=>e.group([e.model.groups[0].id,'c']));assert.equal(e.model.groups.length,1);});
test('M3c rename reorder delete merge and clear are geometry-preserving operations',()=>{const {e}=setup(),l=e.createLayer('Top');e.assignLayer(['a'],l.id);e.renameLayer(l.id,'Hulplijnen');assert.equal(e.model.layers.at(-1).name,'Hulplijnen');const before=plain(e.model.objects);e.removeLayer(l.id);assert.equal(e.model.layers.length,1);assert.deepEqual(plain(e.model.objects),before);assert.throws(()=>e.removeLayer(e.model.layers[0].id));e.model.clear();assert.equal(e.model.layers.length,0);assert.equal(e.toJSON().version,2);});
test('M3c roundtrip with nested groups constructed geometry locks and layer visibility',()=>{const {MI,e}=setup(),m=e.construct('midpoint',[{objectId:'a'},{objectId:'c'}])[0],g=e.group(['a','c']);e.group([g.id,m.id]);e.update('c',{locked:true});const l=e.createLayer('Bronnen');e.assignLayer(['a','c',m.id],l.id);e.setLayerVisibility(l.id,false);const saved=plain(e.toJSON());assert.equal(saved.constructionSchema,1);assert.equal(saved.groupSchema,1);assert.deepEqual(plain(new MI.Engine(saved).toJSON()),saved);});
test('M3c malformed layer schema and membership are rejected atomically',()=>{const {e}=setup();e.createLayer('Valid');const before=plain(e.toJSON());for(const layers of [[],[{id:'a',name:'L',visible:true,members:['a','b','c']}],[{id:'l',name:'L',visible:true,members:['a','b']}],[{id:'l',name:'L',visible:true,members:['a','b','c','missing']}],[{id:'l',name:'L',visible:true,members:['a','b','c']},{id:'q',name:'Q',visible:true,members:['a']}],[{id:'l',name:'L',visible:'false',members:['a','b','c']}],[{id:'l',name:'L',visible:true,members:['a','b','c'],locked:true}]]){assert.throws(()=>e.load({...data(),version:5,layerSchema:1,layers}));assert.deepEqual(plain(e.toJSON()),before);}assert.throws(()=>e.reorderLayers(['missing']));});
test('M3c old opaque layer extensions are preserved rather than silently interpreted',()=>{const {MI}=runtime(),legacy={...data(),version:2,layers:{host:'extension'}};const e=new MI.Engine(legacy);assert.equal(e.model.layers.length,0);assert.deepEqual(plain(e.toJSON().layers),legacy.layers);assert.throws(()=>e.createLayer('Overwrite'));});
test('M3c new and duplicated objects use valid membership and group copies remain together',()=>{const {e}=setup();e.group(['a','b']);const l=e.createLayer('Top');e.assignLayer(['a','b'],l.id);e.setLayerVisibility(l.id,false);const p=e.add({type:'point',x:5,y:1});assert.ok(e.model.layers[0].members.includes(p.id));const copies=e.duplicateMany(['a','b']);assert.ok(e.model.layers[1].members.includes(copies[0].id));assert.ok(e.model.layers[1].members.includes(copies[1].id));e.remove('a');assert.ok(!e.model.layers[1].members.includes('a'));});
test('M3c restricted layer structural commands deny and hidden layer gates direct facade',()=>{const {MI,e}=setup(),l=e.createLayer('Hidden');e.assignLayer(['a'],l.id);e.setLayerVisibility(l.id,false);const {fixture}=require('./permission-fixtures.cjs'),opts=fixture();opts.initialDocument=e.toJSON();opts.policy.parameters={};opts.policy.initialObjectRules={a:{translate:true}};const {session:s,owner}=MI.RuntimeSession.create(opts);assert.equal(s.getObjectCapabilities('a').display,false);assert.equal(s.engine.canSnap('a'),false);assert.throws(()=>s.engine.move('a',1,0));const before=plain(owner.inspect());for(const [operation,payload] of [['layer.create',{name:'Escalate'}],['layer.assign',{ids:['a'],layerId:l.id}],['layer.setVisibility',{id:l.id,value:true}],['layer.rename',{id:l.id,name:'X'}],['layer.reorder',{ids:e.model.layers.map(l=>l.id)}],['layer.delete',{id:l.id}]])assert.throws(()=>s.execute(s.createCommand(operation,payload)),error=>error.code==='MODE_DENIED');assert.deepEqual(plain(owner.inspect()),before);assert.equal(s.engine.toJSON().version,5);assert.equal(s.engine.toJSON().layers.length,2);});
