'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {runtime,plain}=require('./helpers.cjs'),{fixture}=require('./permission-fixtures.cjs');
const owners=new WeakMap();
function make(MI,options){const r=MI.RuntimeSession.create(options);owners.set(r.session,r.owner);return r;}
function setup(profile='course',changes={}){const {MI}=runtime();const {session,owner}=make(MI,fixture(profile,changes));return {MI,session,owner,engine:session.engine};}
function execute(s,operation,payload={}){return s.execute({schema:1,operation,payload,expectedDocumentRevision:s.documentRevision});}
function denied(s,fn,code){const before=plain(owners.get(s).inspect());assert.throws(fn,e=>e.code===code);assert.deepEqual(plain(owners.get(s).inspect()),before);}
test('M2b restricted startup never falls back to author and compiler rejects unknown grants',()=>{const {MI}=runtime();assert.throws(()=>MI.RuntimeSession.create({}),e=>e.code==='INVALID_POLICY');for(const profile of ['course','assessment']){const f=fixture(profile);f.policy.escalate=true;assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');}});
test('M2b defaults and mode ceilings deny direct facade mutation, load, draft and policy spoofing',()=>{for(const profile of ['course','assessment']){const {session:s,engine:e}=setup(profile);for(const fn of [()=>e.update('A',{x:2}),()=>e.remove('A'),()=>e.duplicateMany(['A'])])denied(s,fn,'PERMISSION_DENIED');denied(s,()=>e.load({objects:[]}), 'MODE_DENIED');denied(s,()=>execute(s,'policy.configure',{role:'author'}),'INVALID_COMMAND');assert.equal(e.model.update,undefined);assert.throws(()=>{e.model={};},TypeError);}});
test('M2b move is explicit, property patches cannot use its grant, locks selectable',()=>{const {session:s,engine:e}=setup();assert.equal(s.getObjectCapabilities('L').selectCanvas,true);assert.equal(s.getObjectCapabilities('L').translate,false);e.move('A',1,1);assert.equal(e.get('A').x,1);assert.equal(e.get('M').x,2.5);denied(s,()=>e.move('B',2,2),'PERMISSION_DENIED');});
test('M2b batch mixed permissions is atomic in either order',()=>{for(const ids of [['A','B'],['B','A']]){const {session:s}=setup();denied(s,()=>execute(s,'object.translate',{ids,delta:{x:1,y:1}}),'PERMISSION_DENIED');}});
test('M2b roots translate rigidly; derived requires coverage but not direct geometry grant',()=>{const f=fixture();f.policy.initialObjectRules.B.translate=true;const {MI}=runtime(),{session:s}=make(MI,f);denied(s,()=>execute(s,'object.translate',{ids:['A','M'],delta:{x:1,y:0}}),'INCOMPLETE_GROUP');execute(s,'object.translate',{ids:['A','B','M'],delta:{x:1,y:2}});assert.equal(s.engine.get('M').x,3);assert.equal(s.engine.get('M').y,2);});
test('M2b indirect follow and freeze, protected cascade and typed source gates',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{translate:true,delete:true,sourceTools:['construct:midpoint']},B:{sourceTools:['construct:midpoint']},M:{indirectGeometry:'freeze'}}});denied(s,()=>s.engine.move('A',1,0),'INDIRECT_FROZEN');denied(s,()=>s.engine.remove('A'),'CASCADE_DENIED');const {session:t}=setup();const m=t.engine.construct('midpoint',[{objectId:'A'},{objectId:'B'}])[0];assert.equal(m.construction.kind,'midpoint');denied(t,()=>t.engine.construct('midpoint',[{objectId:'A'},{objectId:'L'}]),'MISSING_SOURCE_PERMISSION');});
test('M2b parameters enforce boundaries step and numeric types without generic field grants',()=>{const {session:s}=setup();execute(s,'parameter.set',{parameterId:'rC',value:2.25});assert.equal(s.engine.get('C').r,2.25);for(const value of [.5,3.5,1.1])denied(s,()=>execute(s,'parameter.set',{parameterId:'rC',value}),'OUT_OF_RANGE');denied(s,()=>execute(s,'parameter.set',{parameterId:'rC',value:'2'}),'INVALID_COMMAND');denied(s,()=>s.engine.update('C',{r:2}),'PERMISSION_DENIED');});
test('M2b creation owns IDs and tool recipes; derived add and spoofed metadata rejected',()=>{const {session:s}=setup();const p=s.engine.add({type:'point',x:2,y:1});assert.ok(p.id);for(const extra of [{id:'A'},{locked:false},{createdBy:'author'},{construction:{kind:'midpoint',sources:[{objectId:'A'},{objectId:'B'}]}}])denied(s,()=>s.engine.add({type:'point',x:0,y:0,...extra}),'INVALID_COMMAND');denied(s,()=>s.engine.add({type:'circle',cx:0,cy:0,r:1}),'PERMISSION_DENIED');});
test('M2b history is private, undo of own create needs no delete grant and reset keeps context',()=>{const {session:s}=setup('assessment',{createdObjectRules:{point:{read:true,display:true,selectCanvas:true}}});const p=s.engine.add({type:'point',x:1,y:1});denied(s,()=>s.engine.remove(p.id),'PERMISSION_DENIED');execute(s,'history.undo');assert.equal(s.engine.get(p.id),null);execute(s,'history.redo');assert.equal(s.engine.get(p.id).x,1);execute(s,'document.reset');assert.equal(s.engine.get(p.id),null);assert.equal(s.activityId,'activity');});
test('M2b preview never mutates committed state, commit checks revisions and handles',()=>{const {session:s,owner}=setup();const c={schema:1,operation:'object.translate',payload:{ids:['A'],delta:{x:0,y:0}},expectedDocumentRevision:s.documentRevision};const h=s.begin(c);const before=plain(owners.get(s).inspect());s.preview(h,{ids:['A'],delta:{x:1,y:0}});assert.equal(s.engine.get('A').x,0);assert.equal(s.previewObject(h,'A').x,1);s.cancel(h);assert.equal(s.engine.get('A').x,0);const h2=s.begin(c);owner.replacePolicy(fixture().policy);assert.throws(()=>s.commit(h2,{ids:['A'],delta:{x:2,y:0}}),e=>e.code==='STALE_TRANSACTION');assert.equal(s.engine.get('A').x,0);assert.equal(before.document.objects.length,s.engine.model.objects.length);});
test('M2b read export is separate from internal snapshots; hidden source closure cannot leak',()=>{const {session:s}=setup('course',{document:{undo:true,reset:true}});denied(s,()=>s.engine.toJSON(),'PERMISSION_DENIED');s.engine.move('A',1,0);execute(s,'history.undo');assert.equal(s.engine.get('A').x,0);const {session:t}=setup('course',{initialObjectRules:{B:{read:false}}});denied(t,()=>t.engine.toJSON(),'PERMISSION_DENIED');});
test('M2b assessment initial deletion and unsupported resume/import policies are rejected',()=>{const {MI}=runtime();for(const change of [{initialObjectRules:{A:{delete:true}}},{document:{draftResume:true}},{allowedTools:['transform:rotate']}]){assert.throws(()=>MI.RuntimeSession.create(fixture('assessment',change)),e=>['INVALID_POLICY','UNSUPPORTED_POLICY'].includes(e.code));}});
test('M2b no public plan application, kernel transaction or opaque metadata leaks',()=>{const {MI}=runtime(),f=fixture();f.initialDocument.meta.answers='private';f.initialDocument.objects[0].answer='private';const {session:s}=make(MI,f);assert.equal(s.apply,undefined);assert.equal(s.transaction,undefined);assert.equal(s.engine.model.meta.answers,undefined);assert.equal(s.engine.get('A').answer,undefined);});
test('M2b field bindings and invalid numeric patches cannot be expanded at commit',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{geometryFields:['x','y']}}});const h=s.begin({schema:1,operation:'object.setGeometry',payload:{id:'A',fields:[{path:'x',value:0}]},expectedDocumentRevision:0});assert.throws(()=>s.commit(h,{id:'A',fields:[{path:'x',value:1},{path:'y',value:1}]}),e=>e.code==='INVALID_COMMAND');s.cancel(h);denied(s,()=>s.engine.update('A',{x:'1'}),'INVALID_COMMAND');});
test('M2b canonical event contains actual direct and indirect effects; failed actions emit none',()=>{const {session:s,owner}=setup();s.engine.move('A',1,1);const event=owner.inspect().events[0];assert.ok(event.directEffects.includes('A'));assert.ok(event.indirectEffects.includes('M'));denied(s,()=>s.engine.move('B',2,2),'PERMISSION_DENIED');});


test('M2b schema is closed against accessors, prototype keys and execution predicates',()=>{const {MI}=runtime();for(const bad of [JSON.parse('{"__proto__":{}}'),{predicate:()=>true}]){const f=fixture();Object.assign(f.policy,bad);assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');}const f=fixture();Object.defineProperty(f.policy,'profile',{get(){throw Error('must not execute');},enumerable:true});assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');});
test('M2b immutable grants cannot conflict or be removed with an object override',()=>{const {MI}=runtime();const f=fixture();f.policy.defaultCapabilities.immutableFields=['x'];assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');});
test('M2b hidden helper parameter is usable without leaking helper or granting selection',()=>{const {MI}=runtime(),f=fixture();f.policy.initialObjectRules.H={read:false,display:false};f.policy.parameters.helper={targets:[{objectId:'H',fieldPath:'x'}],min:0,max:2,initialValue:1};const {session:s,owner}=make(MI,f);execute(s,'parameter.set',{parameterId:'helper',value:2});assert.equal(s.engine.get('H'),null);assert.equal(owner.inspect().document.objects.find(o=>o.id==='H').x,2);assert.equal(s.getObjectCapabilities('H').selectCanvas,false);});
test('M2b invalid hidden or unreadable objects cannot be sources or direct mutation targets',()=>{const {session:s}=setup();denied(s,()=>execute(s,'object.translate',{ids:['H'],delta:{x:1,y:0}}),'OBJECT_NOT_AVAILABLE');denied(s,()=>s.engine.construct('midpoint',[{objectId:'A'},{objectId:'H'}]),'OBJECT_NOT_AVAILABLE');assert.equal(s.getObjectCapabilities('H').selectList,false);});
test('M2b display and selection are independently gated from snap',()=>{const {MI}=runtime(),f=fixture();f.policy.initialObjectRules.A={translate:true,selectCanvas:false,snap:true};const {session:s}=make(MI,f);assert.equal(s.engine.selectAt(0,0,.01),null);assert.equal(s.engine.canSnap('A'),true);assert.deepEqual(plain(execute(s,'object.select',{ids:['A','L','unknown'],source:'canvas'}).selectedIds),['L']);});
test('M2b mixed properties and geometry cannot partially apply',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{propertyFields:['style.stroke']}}});denied(s,()=>s.engine.update('A',{style:{stroke:'#ff0000'},x:2}),'PERMISSION_DENIED');s.engine.update('A',{style:{stroke:'#ff0000'}});assert.equal(s.engine.get('A').style.stroke,'#ff0000');});
test('M2b property values require explicit numeric and boolean types',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{propertyFields:['style.opacity','showLabel','labelOffsetX']}}});for(const patch of [{style:{opacity:'0.5'}},{showLabel:'false'},{labelOffsetX:'1'}])denied(s,()=>s.engine.update('A',patch),'INVALID_COMMAND');s.engine.update('A',{labelOffsetX:null});assert.equal(s.engine.get('A').labelOffsetX,null);});
test('M2b permitted field mutation still enforces shared parameter domains',()=>{const {session:s}=setup('course',{initialObjectRules:{C:{geometryFields:['r']}}});denied(s,()=>s.engine.update('C',{r:4}),'OUT_OF_RANGE');s.engine.update('C',{r:3});assert.equal(s.engine.get('C').r,3);});
test('M2b invalid parameter configurations and overlapping bindings fail startup',()=>{const {MI}=runtime();for(const change of ['locked','derived','overlap','offstep']){const f=fixture();if(change==='locked')f.initialDocument.objects.find(o=>o.id==='C').locked=true;if(change==='derived')f.policy.parameters.rC.targets=[{objectId:'M',fieldPath:'x'}];if(change==='overlap')f.policy.parameters.other=f.policy.parameters.rC;if(change==='offstep')f.policy.parameters.rC.min=.1;assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');}});
test('M2b triangle tool is an exact recipe rather than polygon alias',()=>{const {MI}=runtime(),f=fixture();f.policy.allowedTools=['create:triangle'];f.policy.createdObjectRules.polygon={read:true,display:true};const {session:s}=make(MI,f),vertices=[{x:0,y:0},{x:2,y:0},{x:0,y:2}];denied(s,()=>s.engine.add({type:'polygon',vertices}),'PERMISSION_DENIED');execute(s,'object.create',{toolId:'create:triangle',object:{type:'polygon',vertices}});denied(s,()=>execute(s,'object.create',{toolId:'create:triangle',object:{type:'polygon',vertices:[...vertices,{x:-1,y:1}]}}),'INVALID_COMMAND');});
test('M2b optional initial style requires the same property grant',()=>{const {session:s}=setup();denied(s,()=>s.engine.add({type:'point',x:1,y:1,style:{stroke:'#ff0000'}}),'PERMISSION_DENIED');});
test('M2b delete checks entire dependent closure and author cascade remains compatible',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{delete:true},M:{delete:true}}});s.engine.remove('A');assert.equal(s.engine.get('A'),null);assert.equal(s.engine.get('M'),null);assert.equal(s.engine.get('B').x,4);execute(s,'history.undo');assert.equal(s.engine.get('M').x,2);});
test('M2b derived duplication never detaches a protected graph',()=>{const {session:s}=setup('course',{initialObjectRules:{M:{duplicate:true}}});denied(s,()=>s.engine.duplicateMany(['M']),'MODE_DENIED');});
test('M2b budgets reject complete batches and preserve IDs history and events',()=>{const {MI}=runtime(),f=fixture();f.policy.limits.maxObjects=f.initialDocument.objects.length;const {session:s}=make(MI,f);denied(s,()=>s.engine.add({type:'point',x:1,y:1}),'INVALID_COMMAND');const f2=fixture();f2.policy.limits.maxBatchObjects=1;f2.policy.initialObjectRules.B.translate=true;const {session:t}=make(MI,f2);denied(t,()=>execute(t,'object.translate',{ids:['A','B'],delta:{x:1,y:1}}),'INVALID_COMMAND');});
test('M2b policy epoch invalidates history and cached readable facade',()=>{const {session:s,owner}=setup();s.engine.move('A',1,0);assert.ok(s.engine.model.get('A'));const p=fixture().policy;p.initialObjectRules.A={read:false,display:false};owner.replacePolicy(p);assert.equal(s.engine.model.get('A'),null);assert.equal(s.canUndo,false);denied(s,()=>execute(s,'history.undo'),'UNTRUSTED_HISTORY');});
test('M2b transaction belongs to one session and expires on a committed command',()=>{const {session:s}=setup(),{session:t}=setup();const h=s.begin(s.createCommand('object.translate',{ids:['A'],delta:{x:0,y:0}}));assert.throws(()=>t.commit(h,{ids:['A'],delta:{x:1,y:0}}),e=>e.code==='STALE_TRANSACTION');s.engine.add({type:'point',x:2,y:2});assert.throws(()=>s.commit(h,{ids:['A'],delta:{x:1,y:0}}),e=>e.code==='STALE_TRANSACTION');assert.equal(s.engine.get('A').x,0);});
test('M2b renderer bounds and nested snapshots cannot mutate canonical state',()=>{const {session:s}=setup();const before=plain(owners.get(s).inspect());assert.throws(()=>{s.engine.renderer.bounds.xMin=-100;},TypeError);assert.throws(()=>{s.engine.renderer.showGrid=true;},TypeError);assert.throws(()=>s.engine.renderer.setBounds({xMin:0,xMax:1,yMin:0,yMax:1}),e=>e.code==='MODE_DENIED');const object=s.engine.get('A');object.x=100;assert.deepEqual(plain(owners.get(s).inspect()),before);});
test('M2b view changes never mutate canonical document or create history',()=>{const {session:s,owner}=setup();const before=plain(owner.inspect());execute(s,'view.zoom',{bounds:{xMin:-1,xMax:1,yMin:-1,yMax:1}});assert.equal(s.engine.renderer.bounds.xMin,-1);assert.deepEqual(plain(owner.inspect().document),before.document);assert.equal(s.canUndo,false);execute(s,'document.reset');assert.equal(s.engine.renderer.bounds.xMin,before.document.presentation.bounds.xMin);});
test('M2b dispose permanently invalidates learner commands',()=>{const {session:s,owner}=setup();owner.dispose();denied(s,()=>s.engine.move('A',1,1),'STALE_TRANSACTION');});
test('M2b summative uses explicit host kind with same default-deny local semantics',()=>{const {MI}=runtime(),f=fixture('assessment');f.assessmentKind='summative';const {session:s}=make(MI,f);denied(s,()=>s.engine.update('B',{x:2}),'PERMISSION_DENIED');assert.equal(s.engine.get('B').x,4);});

test('M2b both tangent branches are atomic including result allocation budget',()=>{const {MI}=runtime(),f=fixture();f.initialDocument.objects.find(o=>o.id==='A').x=-2;const circle=f.initialDocument.objects.find(o=>o.id==='C');circle.cx=0;circle.cy=0;f.policy.allowedTools=['construct:tangent'];f.policy.createdObjectRules.straight={read:true,display:true};f.policy.initialObjectRules.A.sourceTools=['construct:tangent'];f.policy.initialObjectRules.C.sourceTools=['construct:tangent'];f.policy.limits.maxObjects=7;const {session:s}=make(MI,f);denied(s,()=>s.engine.construct('tangent',[{objectId:'C'},{objectId:'A'}]),'INVALID_COMMAND');f.policy.limits.maxObjects=8;const {session:t}=make(MI,f);assert.equal(t.engine.construct('tangent',[{objectId:'C'},{objectId:'A'}]).length,2);});
test('M2b indirect invalidity is rejected or recoverable according to explicit policy',()=>{for(const allow of [false,true]){const {MI}=runtime(),f=fixture();f.initialDocument.objects.find(o=>o.id==='A').x=-2;const circle=f.initialDocument.objects.find(o=>o.id==='C');circle.cx=0;circle.cy=0;f.initialDocument.objects.push({id:'T',type:'straight',x1:0,y1:0,x2:1,y2:1,construction:{kind:'tangent',sources:[{objectId:'C'},{objectId:'A'}],branch:0}});f.policy.initialObjectRules.T={allowIndirectInvalid:allow};const {session:s}=make(MI,f);if(!allow)denied(s,()=>s.engine.move('A',0,0),'WOULD_INVALIDATE');else{s.engine.move('A',0,0);assert.equal(s.engine.get('T').constructionValid,false);assert.equal(s.getObjectCapabilities('T').selectCanvas,false);s.engine.move('A',-2,0);assert.equal(s.engine.get('T').constructionValid,true);}}});
test('M2b freeze permits a no-op and canonical effects reflect authoritative calculator',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{translate:true},M:{indirectGeometry:'freeze'}}});s.engine.move('A',0,0);assert.equal(s.documentRevision,0);});
test('M2b right-angle geometry patches validate final shape atomically',()=>{const {MI}=runtime(),f=fixture();f.initialDocument.objects.push({id:'R',type:'angle',angleMark:'right',vertices:[{x:-1,y:0},{x:0,y:0},{x:0,y:1}]});f.policy.initialObjectRules.R={geometryFields:['vertices[0].x','vertices[0].y','vertices[1].x','vertices[1].y','vertices[2].x','vertices[2].y']};const {session:s}=make(MI,f);s.engine.update('R',{vertices:[{x:0,y:1},{x:1,y:1},{x:1,y:2}]});assert.equal(s.engine.get('R').vertices[1].x,1);});
test('M2b reset and history are append-only evidence with deterministic local digests',()=>{const {session:s,owner}=setup();s.engine.move('A',1,0);execute(s,'history.undo');execute(s,'history.redo');execute(s,'document.reset');execute(s,'document.reset');const events=owner.inspect().events;assert.equal(events.length,5);assert.equal(events[1].historyAction,'undo');assert.ok(events.every(e=>/^fnv1a32:/.test(e.preDigest)));assert.equal(events[4].operation,'document.reset');});
test('M2b creation projection strips nested extension data from duplication results',()=>{const {MI}=runtime(),f=fixture();f.initialDocument.objects[0].secret='answer';f.initialDocument.objects[0].style={extension:{secret:'answer'}};f.policy.initialObjectRules.A.duplicate=true;const {session:s}=make(MI,f);const copy=s.engine.duplicateMany(['A'])[0];assert.equal(copy.secret,undefined);assert.equal(copy.style.extension,undefined);});
test('M2b malformed closed commands cannot spoof role effects history or operator',()=>{const {session:s}=setup();for(const extra of [{actorId:'teacher'},{role:'author'},{fromHistory:true},{effects:[]}])denied(s,()=>s.execute({...s.createCommand('object.translate',{ids:['A'],delta:{x:1,y:0}}),...extra}),'INVALID_COMMAND');denied(s,()=>execute(s,'transform.rotate',{ids:['A']}),'UNSUPPORTED_COMMAND');});

test('M2b host must explicitly provide a baseline and authorized plans remain private',()=>{const {MI}=runtime(),f=fixture();delete f.initialDocument;assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');assert.equal(MI.PermissionEvaluator.authorizeCommand,undefined);});
test('M2b author-ui commands enforce locks while trusted legacy engine remains compatible',()=>{const {MI}=runtime(),e=new MI.Engine({objects:[{id:'L',type:'point',x:0,y:0,locked:true}]});e.update('L',{x:1});assert.equal(e.get('L').x,1);const a=MI.AuthorCommands(e);for(const operation of ['object.setGeometry','object.setProperties','object.delete']){const payload=operation==='object.setGeometry'?{id:'L',fields:[{path:'x',value:2}]}:operation==='object.setProperties'?{ids:['L'],fields:[{path:'name',value:'test'}]}:{ids:['L']};assert.throws(()=>a.execute(a.createCommand(operation,payload)),error=>error.code==='LOCKED');}a.execute(a.createCommand('object.setVisibility',{ids:['L'],value:false}));assert.equal(e.get('L').visible,false);assert.equal(a.execute(a.createCommand('object.duplicate',{ids:['L']})).result.length,1);});
