'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {runtime,plain}=require('./helpers.cjs'),{fixture}=require('./permission-fixtures.cjs');
const owners=new WeakMap();
function make(MI,options){const r=MI.RuntimeSession.create(options);owners.set(r.session,r.owner);return r;}
function setup(profile='course',changes={}){const {MI}=runtime();const {session,owner}=make(MI,fixture(profile,changes));return {MI,session,owner,engine:session.engine};}
function execute(s,operation,payload={}){return s.execute({schema:1,operation,payload,expectedDocumentRevision:s.documentRevision});}
function denied(s,fn,code){const before=plain(owners.get(s).inspect());assert.throws(fn,e=>e.code===code);assert.deepEqual(plain(owners.get(s).inspect()),before);}
test('M2b restricted startup never falls back to author and compiler rejects unknown grants',()=>{const {MI}=runtime();assert.throws(()=>MI.RuntimeSession.create({}),e=>e.code==='INVALID_POLICY');for(const profile of ['course','assessment']){const f=fixture(profile);f.policy.escalate=true;assert.throws(()=>MI.RuntimeSession.create(f),e=>e.code==='INVALID_POLICY');}});
test('M2b defaults and mode ceilings deny direct facade mutation, load, draft and policy spoofing',()=>{for(const profile of ['course','assessment']){const {session:s,engine:e}=setup(profile);for(const fn of [()=>e.update('A',{x:2}),()=>e.remove('A'),()=>e.duplicateMany(['A'])])denied(s,fn,'PERMISSION_DENIED');denied(s,()=>e.load({objects:[]}), 'MODE_DENIED');denied(s,()=>execute(s,'policy.configure',{role:'author'}),'INVALID_COMMAND');assert.equal(e.model.update,undefined);assert.throws(()=>{e.model={};},TypeError);}});
test('M2b move is explicit, property patches cannot use its grant, locks selectable',()=>{const {session:s,engine:e}=setup();assert.equal(s.getObjectCapabilities('L').selectCanvas,true);assert.equal(s.getObjectCapabilities('L').translate,false);e.move('A',1,1);assert.equal(e.get('A').x,1);assert.equal(e.get('M').x,2.5);denied(s,()=>e.move('B',2,2),'PERMISSION_DENIED');});
test('M2b batch mixed permissions is atomic in either order',()=>{for(const ids of [['A','B'],['B','A']]){const {session:s}=setup();denied(s,()=>execute(s,'object.translate',{ids,delta:{x:1,y:1}}),'PERMISSION_DENIED');}});
test('M2b roots translate rigidly; derived requires coverage but not direct geometry grant',()=>{const f=fixture();f.policy.initialObjectRules.B.translate=true;const {MI}=runtime(),{session:s}=make(MI,f);denied(s,()=>execute(s,'object.translate',{ids:['A','M'],delta:{x:1,y:0}}),'INCOMPLETE_GROUP');execute(s,'object.translate',{ids:['A','B','M'],delta:{x:1,y:2}});assert.equal(s.engine.get('M').x,3);assert.equal(s.engine.get('M').y,2);});
test('M2b indirect follow and freeze, protected cascade and typed source gates',()=>{const {session:s}=setup('course',{initialObjectRules:{A:{translate:true,delete:true,sourceTools:['construct:midpoint']},B:{sourceTools:['construct:midpoint']},M:{indirectGeometry:'freeze'}}});denied(s,()=>s.engine.move('A',1,0),'INDIRECT_FROZEN');denied(s,()=>s.engine.remove('A'),'CASCADE_DENIED');const {session:t}=setup();const m=t.engine.construct('midpoint',[{objectId:'A'},{objectId:'B'}])[0];assert.equal(m.construction.kind,'midpoint');denied(t,()=>t.engine.construct('midpoint',[{objectId:'A'},{objectId:'L'}]),'MISSING_SOURCE_PERMISSION');});
test('M2b parameters enforce boundaries step and numeric types without generic field grants',()=>{const {session:s}=setup();execute(s,'parameter.set',{parameterId:'rC',value:2.25});assert.equal(s.engine.get('C').r,2.25);for(const value of [.5,3.5,1.1])denied(s,()=>execute(s,'parameter.set',{parameterId:'rC',value}),'OUT_OF_RANGE');denied(s,()=>execute(s,'parameter.set',{parameterId:'rC',value:'2'}),'INVALID_COMMAND');denied(s,()=>s.engine.update('C',{r:2}),'PERMISSION_DENIED');});
test('M2b creation owns IDs and tool recipes; derived add and spoofed metadata rejected',()=>{const {session:s}=setup();const p=s.engine.add({type:'point',x:2,y:1});assert.ok(p.id);for(const extra of [{id:'A'},{locked:false},{createdBy:'author'},{construction:{kind:'midpoint',sources:[{objectId:'A'},{objectId:'B'}]}}])denied(s,()=>s.engine.add({type:'point',x:0,y:0,...extra}),'INVALID_COMMAND');denied(s,()=>s.engine.add({type:'circle',cx:0,cy:0,r:1}),'PERMISSION_DENIED');});
test('M2b history is private, undo of own create needs no delete grant and reset keeps context',()=>{const {session:s}=setup('assessment',{createdObjectRules:{point:{read:true,display:true,selectCanvas:true}}});const p=s.engine.add({type:'point',x:1,y:1});denied(s,()=>s.engine.remove(p.id),'PERMISSION_DENIED');execute(s,'history.undo');assert.equal(s.engine.get(p.id),null);execute(s,'history.redo');assert.equal(s.engine.get(p.id).x,1);execute(s,'document.reset');assert.equal(s.engine.get(p.id),null);assert.equal(s.activityId,'activity');});
test('M2b preview never mutates committed state, commit checks revisions and handles',()=>{const {session:s,owner}=setup();const c={schema:1,operation:'object.translate',payload:{ids:['A'],delta:{x:0,y:0}},expectedDocumentRevision:s.documentRevision};const h=s.begin(c);const before=plain(owners.get(s).inspect());s.preview(h,{ids:['A'],delta:{x:1,y:0}});assert.equal(s.engine.get('A').x,0);assert.equal(s.previewObject(h,'A').x,1);s.cancel(h);assert.equal(s.engine.get('A').x,0);const h2=s.begin(c);owner.replacePolicy(fixture().policy);assert.throws(()=>s.commit(h2,{ids:['A'],delta:{x:2,y:0}}),e=>e.code==='STALE_TRANSACTION');assert.equal(s.engine.get('A').x,0);assert.equal(before.document.objects.length,s.engine.model.objects.length);});
test('M2b read export is separate from internal snapshots; hidden source closure cannot leak',()=>{const {session:s}=setup('course',{document:{undo:true,reset:true}});denied(s,()=>s.engine.toJSON(),'PERMISSION_DENIED');s.engine.move('A',1,0);execute(s,'history.undo');assert.equal(s.engine.get('A').x,0);const {session:t}=setup('course',{initialObjectRules:{B:{read:false}}});denied(t,()=>t.engine.toJSON(),'PERMISSION_DENIED');});
test('M2b assessment initial deletion and unsupported resume/import policies are rejected',()=>{const {MI}=runtime();for(const change of [{initialObjectRules:{A:{delete:true}}},{document:{draftResume:true}},{allowedTools:['transform:rotate']}]){assert.throws(()=>MI.RuntimeSession.create(fixture('assessment',change)),e=>['INVALID_POLICY','UNSUPPORTED_POLICY'].includes(e.code));}});
