const test=require('node:test'),assert=require('node:assert/strict');
const {runtime,plain}=require('./helpers.cjs');
const data=()=>({objects:['a','b','c','d'].map((id,i)=>({id,type:'point',x:i,y:0}))});
function setup(){const {MI}=runtime();return {MI,e:new MI.Engine(data())};}
test('M3b groups have separate IDs and preserve geometry and SVG',()=>{const {e}=setup(),svg=e.renderSVG(),objects=plain(e.model.objects);const g=e.group(['a','b']);assert.deepEqual(plain(g.members),['a','b']);assert.notEqual(g.id,'a');assert.deepEqual(plain(e.model.objects),objects);assert.equal(e.renderSVG(),svg);assert.equal(e.toJSON().version,4);assert.equal(e.toJSON().groupSchema,1);});
test('M3b nested grouping and one-level ungroup preserve child membership',()=>{const {e}=setup();const child=e.group(['a','b']);const parent=e.group([child.id,'c']);assert.equal(e.model.groups.length,2);assert.deepEqual(plain(e.groupMembers(parent.id)),['a','b','c']);e.ungroup([parent.id]);assert.equal(e.model.groups.length,1);assert.equal(e.model.groups[0].id,child.id);});
test('M3b overlapping dangling cyclic duplicate and colliding group graphs are atomically rejected',()=>{const {e}=setup();const before=plain(e.toJSON());for(const groups of [[{id:'g',name:'G',members:['a','missing']}],[{id:'g',name:'G',members:['a','a']}],[{id:'a',name:'G',members:['b','c']}],[{id:'g',name:'G',members:['a','b']},{id:'h',name:'H',members:['a','c']}],[{id:'g',name:'G',members:['h','a']},{id:'h',name:'H',members:['g','b']}]]){assert.throws(()=>e.load({...data(),version:4,groupSchema:1,groups}));assert.deepEqual(plain(e.toJSON()),before);}});
test('M3b group mutation cannot steal a member and keeps allocator stable on refusal',()=>{const {e}=setup();e.group(['a','b']);const before=plain(e.toJSON()),counter=e.model._nextId;assert.throws(()=>e.group(['a','c']));assert.deepEqual(plain(e.toJSON()),before);assert.equal(e.model._nextId,counter);});
test('M3b v4 nested groups roundtrip and ungroup returns to legacy geometry version',()=>{const {MI,e}=setup();const g=e.group(['a','b']);e.group([g.id,'c']);const saved=plain(e.toJSON()),copy=new MI.Engine(saved);assert.deepEqual(plain(copy.toJSON()),saved);copy.ungroup(copy.model.groups.map(g=>g.id));assert.equal(copy.toJSON().version,2);assert.equal(copy.model.groups.length,0);});
test('M3b object deletion prunes memberships and dissolves single-member groups',()=>{const {e}=setup();const inner=e.group(['a','b']);e.group([inner.id,'c']);e.remove('a');assert.equal(e.model.groups.length,1);assert.deepEqual(plain(e.model.groups[0].members),['b','c']);e.remove('b');assert.equal(e.model.groups.length,0);assert.ok(e.get('c'));});
test('M3b duplicating complete groups copies hierarchy without stealing original members',()=>{const {e}=setup(),g=e.group(['a','b']);e.group([g.id,'c']);const copies=e.duplicateMany(['a','b','c']);assert.equal(e.model.groups.length,4);assert.deepEqual(plain(e.groupMembers(e.model.groups.at(-1).id)),copies.map(o=>o.id));assert.equal(e.get('a').x,0);});
test('M3b legacy opaque group extensions are preserved and cannot be overwritten by group creation',()=>{const {MI}=runtime(),legacy={...data(),version:2,groups:{external:'opaque'}};const e=new MI.Engine(legacy);assert.equal(e.model.groups.length,0);assert.deepEqual(plain(e.toJSON().groups),legacy.groups);assert.throws(()=>e.group(['a','b']));});
test('M3b author semantic group commands and locked member movement gate',()=>{const {MI,e}=setup(),c=MI.AuthorCommands(e),g=c.execute(c.createCommand('group.create',{members:['a','b'],name:'Named'})).result;e.update('b',{locked:true});assert.equal(c.canExecute(c.createCommand('object.translate',{ids:['a','b'],delta:{x:1,y:1}})).allowed,false);c.execute(c.createCommand('group.ungroup',{ids:[g.id]}));assert.equal(e.model.groups.length,0);});
test('M3b restricted structural commands deny, projected groups retain read closure and export schema',()=>{const {MI,e}=setup();e.group(['a','b']);const {fixture}=require('./permission-fixtures.cjs');const opts=fixture();opts.initialDocument=e.toJSON();opts.policy.initialObjectRules={a:{translate:true},b:{translate:true}};opts.policy.parameters={};const {session:s,owner}=MI.RuntimeSession.create(opts);assert.equal(s.engine.model.groups.length,1);for(const operation of ['group.create','group.ungroup']){const before=plain(owner.inspect());assert.throws(()=>s.execute(s.createCommand(operation,operation==='group.create'?{members:['c','d'],name:'Escalate'}:{ids:[e.model.groups[0].id]})),error=>error.code==='MODE_DENIED');assert.deepEqual(plain(owner.inspect()),before);}assert.equal(s.engine.toJSON().version,4);assert.equal(s.engine.toJSON().groups.length,1);assert.equal(s.canExecute(s.createCommand('object.translate',{ids:['a'],delta:{x:1,y:0}})).allowed,false);});
