const test=require('node:test');
const assert=require('node:assert/strict');
const {runtime,plain}=require('./helpers.cjs');
function setup(){const {MI}=runtime();return {MI,s:MI.RectangleSelection,t:{mathToScreen:p=>({...p}),screenToMath:p=>({...p})},bounds:{xMin:-10,xMax:10,yMin:-10,yMax:10}};}
const rect=(x1,y1,x2,y2)=>({left:Math.min(x1,x2),right:Math.max(x1,x2),top:Math.min(y1,y2),bottom:Math.max(y1,y2)});
function hit(o,r,mode='cross'){const {s,t,bounds}=setup();return s.hits(o,r,mode,{transform:t,bounds});}
test('M1 point containment includes boundaries and excludes outside',()=>{assert.equal(hit({type:'point',x:1,y:1},rect(0,0,1,1),'contain'),true);assert.equal(hit({type:'point',x:2,y:1},rect(0,0,1,1)),false);});
test('M1 segments use geometry rather than bounding boxes',()=>{const o={type:'line',x1:0,y1:0,x2:4,y2:4};assert.equal(hit(o,rect(0,3,1,4)),false);assert.equal(hit(o,rect(1,1,2,2)),true);assert.equal(hit(o,rect(1,1,2,2),'contain'),false);});
test('M1 circle tests reject empty bounding-box corners and include tangency/interior',()=>{const o={type:'circle',cx:0,cy:0,r:2};assert.equal(hit(o,rect(1.8,1.8,2,2)),false);assert.equal(hit(o,rect(2,-.1,3,.1)),true);assert.equal(hit(o,rect(-.1,-.1,.1,.1)),true);assert.equal(hit(o,rect(-2,-2,2,2),'contain'),true);});
test('M1 concave polygons use edges and interior rather than bounds',()=>{const o={type:'polygon',vertices:[{x:0,y:0},{x:4,y:0},{x:4,y:1},{x:1,y:1},{x:1,y:4},{x:0,y:4}]};assert.equal(hit(o,rect(2,2,3,3)),false);assert.equal(hit(o,rect(.2,2,.8,3)),true);assert.equal(hit(o,rect(-1,-1,5,5),'contain'),true);});
test('M1 straight and ray respect visible viewport and forward domain',()=>{const o={type:'straight',x1:0,y1:0,x2:1,y2:0};assert.equal(hit(o,rect(-8,-1,-7,1)),true);assert.equal(hit({...o,type:'ray'},rect(-8,-1,-7,1)),false);assert.equal(hit(o,rect(-10,-1,10,1),'contain'),true);assert.equal(hit(o,rect(-1,-1,1,1),'contain'),false);});
test('M1 hidden invalid and degenerate geometry cannot be canvas selected; locked can',()=>{for(const o of [{type:'point',x:0,y:0,visible:false},{type:'point',x:NaN,y:0},{type:'circle',cx:0,cy:0,r:-1},{type:'line',x1:0,y1:0,x2:0,y2:0},{type:'point',x:0,y:0,construction:{kind:'midpoint'},constructionValid:false}])assert.equal(hit(o,rect(-1,-1,1,1)),false);assert.equal(hit({type:'point',x:0,y:0,locked:true},rect(-1,-1,1,1)),true);});
test('M1 modifier precedence and deterministic immutable base selection',()=>{const {s}=setup();assert.equal(s.operation({ctrlKey:true,shiftKey:true}),'toggle');assert.equal(s.operation({metaKey:true,shiftKey:true}),'toggle');assert.equal(s.operation({shiftKey:true}),'add');assert.deepEqual(plain(s.combine(['a','b'],['b','c'],'toggle')),['a','c']);assert.deepEqual(plain(s.combine(['a','b'],['b','c'],'add')),['a','b','c']);assert.deepEqual(plain(s.combine(['a'],['b'],'replace')),['b']);});
test('M1 affine screen transforms preserve circle and polygon tests',()=>{const {s,bounds}=setup(),t={mathToScreen:p=>({x:2*p.x+p.y+30,y:3*p.y+20}),screenToMath:p=>({x:((p.x-30)-(p.y-20)/3)/2,y:(p.y-20)/3})};assert.equal(s.hits({type:'circle',cx:0,cy:0,r:1},rect(27,16,33,24),'contain',{transform:t,bounds}),true);assert.equal(s.hits({type:'circle',cx:0,cy:0,r:1},rect(32,23,33,24),'cross',{transform:t,bounds}),false);});
test('M1 text selection uses supplied rotated glyph quadrilateral',()=>{const {s,t,bounds}=setup(),o={id:'t',type:'text',x:0,y:0};const textGeometry={t:[{x:0,y:2},{x:2,y:0},{x:4,y:2},{x:2,y:4}]};assert.equal(s.hits(o,rect(0,0,.5,.5),'cross',{transform:t,bounds,textGeometry}),false);assert.equal(s.hits(o,rect(-1,-1,5,5),'contain',{transform:t,bounds,textGeometry}),true);});
test('M1 angle arc and right marker can be touched away from arms',()=>{const o={type:'angle',vertices:[{x:2,y:0},{x:0,y:0},{x:0,y:2}]};assert.equal(hit(o,rect(.48,.48,.51,.51)),true);assert.equal(hit({...o,angleMark:'right'},rect(.68,.4,.72,.5)),true);assert.equal(hit(o,rect(.6,.6,.65,.65)),false);});
test('M1 semicircle angle marker extends beyond the collinear arm bounds',()=>{const o={type:'angle',vertices:[{x:2,y:0},{x:0,y:0},{x:-2,y:0}]};assert.equal(hit(o,rect(-2,-.1,2,.1),'contain'),false);});
