/* From Zero 2 Infinity — Mathematical Illustration Editor */
(function (global) {
  "use strict";
  const MI=global.FZI.MathIllustration, STORAGE_KEY="fzi.mathIllustration.draft";
  const canvas=document.getElementById("canvas"), canvasWrap=document.getElementById("canvasWrap"), status=document.getElementById("status"), objectCount=document.getElementById("objectCount"), selectionPanel=document.getElementById("selectionPanel"), titleInput=document.getElementById("titleInput"), descriptionInput=document.getElementById("descriptionInput"), crosshair=document.getElementById("crosshair"), axesBtn=document.getElementById("axesBtn"), gridBtn=document.getElementById("gridBtn");
  const xMinInput=document.getElementById("xMinInput"),xMaxInput=document.getElementById("xMaxInput"),yMinInput=document.getElementById("yMinInput"),yMaxInput=document.getElementById("yMaxInput");
  let engine=new MI.Engine(null,{width:1000,height:650,bounds:{xMin:-5,yMin:-3,xMax:5,yMax:3},background:"#f7f7f4",padding:30,showAxes:true,showGrid:false,axisStep:1});
  let tool="select",selectedId=null,drag=null;
  function setStatus(m){status.textContent=m;}
  function fmt(v){return Number(v).toFixed(1);}
  function updateViewButtons(){axesBtn.textContent=engine.renderer.showAxes?"Assen verbergen":"Assen tonen";gridBtn.textContent=engine.renderer.showGrid?"Raster verbergen":"Raster tonen";}
  function updateBoundsInputs(){const b=engine.renderer.bounds;xMinInput.value=fmt(b.xMin);xMaxInput.value=fmt(b.xMax);yMinInput.value=fmt(b.yMin);yMaxInput.value=fmt(b.yMax);}
  function pointerPosition(event){const svg=canvas.querySelector("svg");if(!svg)return null;const matrix=svg.getScreenCTM();if(!matrix)return null;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse()),r=engine.renderer,b=r.bounds,dw=r.width-r.padding*2,dh=r.height-r.padding*2;return{x:b.xMin+((p.x-r.padding)/dw)*(b.xMax-b.xMin),y:b.yMin+((r.height-r.padding-p.y)/dh)*(b.yMax-b.yMin)};}
  function updateMeta(){engine.model.meta.title=titleInput.value.trim();engine.model.meta.description=descriptionInput.value.trim();}
  function render(){updateMeta();canvas.innerHTML=engine.renderSVG();objectCount.textContent=engine.model.objects.length+(engine.model.objects.length===1?" object":" objecten");updateViewButtons();updateBoundsInputs();if(selectedId){const s=canvas.querySelector('[data-object-id="'+CSS.escape(selectedId)+'"]');if(s)s.classList.add("selected");}renderSelectionPanel();}
  function renderSelectionPanel(){const o=selectedId?engine.get(selectedId):null;if(!o){selectionPanel.className="selection-empty";selectionPanel.textContent="Geen object geselecteerd.";return;}selectionPanel.className="selection-panel";let h="<div><strong>"+o.type+"</strong> <code>"+o.id+"</code>"+(o.label?" · "+o.label:"")+"</div>";if(o.type==="point"||o.type==="text")h+=field("x",o.x,"x")+field("y",o.y,"y");if(o.type==="line")h+=field("x₁",o.x1,"x1")+field("y₁",o.y1,"y1")+field("x₂",o.x2,"x2")+field("y₂",o.y2,"y2");if(o.type==="circle")h+=field("cx",o.cx,"cx")+field("cy",o.cy,"cy")+field("r",o.r,"r");if(o.type==="text")h+='<label>Tekst<input data-edit="text" value="'+MI.escapeXml(o.text)+'"></label>';if(o.label!=null)h+='<label>Label<input data-edit="label" value="'+MI.escapeXml(o.label)+'"></label>';h+='<button class="delete-btn" id="deleteSelected">Verwijder object</button>';selectionPanel.innerHTML=h;selectionPanel.querySelectorAll("[data-edit]").forEach(i=>i.addEventListener("change",()=>{const patch={};patch[i.dataset.edit]=i.type==="text"?i.value:Number(i.value);engine.update(o.id,patch);render();}));const db=document.getElementById("deleteSelected");if(db)db.addEventListener("click",()=>{engine.remove(o.id);selectedId=null;render();setStatus("Object verwijderd.");});}
  function field(label,value,key){return '<div class="row"><span>'+label+'</span><input data-edit="'+key+'" type="number" step="0.1" value="'+fmt(value)+'"></div>';}
  function activateTool(next){tool=next;document.querySelectorAll(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===tool));setStatus(tool==="select"?"Selecteer een object.":"Teken: "+tool+".");}
  function finishLine(s,e){if(Math.hypot(e.x-s.x,e.y-s.y)<0.05)return;engine.renderer.preview=null;selectedId=engine.add({type:"line",x1:s.x,y1:s.y,x2:e.x,y2:e.y}).id;render();setStatus("Lijnstuk toegevoegd.");}
  function finishCircle(c,e){const r=Math.hypot(e.x-c.x,e.y-c.y);if(r<0.05)return;engine.renderer.preview=null;selectedId=engine.add({type:"circle",cx:c.x,cy:c.y,r:r}).id;render();setStatus("Cirkel toegevoegd.");}
  function applyBounds(){let xmin=Number(xMinInput.value),xmax=Number(xMaxInput.value),ymin=Number(yMinInput.value),ymax=Number(yMaxInput.value);if(!Number.isFinite(xmin)||!Number.isFinite(xmax)||!Number.isFinite(ymin)||!Number.isFinite(ymax)||xmin>=xmax||ymin>=ymax){setStatus("Ongeldig coördinatenbereik.");updateBoundsInputs();return;}engine.renderer.bounds={xMin:xmin,yMin:ymin,xMax:xmax,yMax:ymax};render();setStatus("Coördinatenbereik toegepast.");}
  function zoomAt(event){if(drag)return;event.preventDefault();const p=pointerPosition(event);if(!p)return;const b=engine.renderer.bounds, factor=event.deltaY<0?0.85:1/0.85, nx=(b.xMax-b.xMin)*factor, ny=(b.yMax-b.yMin)*factor, fx=(p.x-b.xMin)/(b.xMax-b.xMin), fy=(p.y-b.yMin)/(b.yMax-b.yMin);engine.renderer.bounds={xMin:p.x-fx*nx,xMax:p.x+(1-fx)*nx,yMin:p.y-fy*ny,yMax:p.y+(1-fy)*ny};render();}
  canvasWrap.addEventListener("wheel",zoomAt,{passive:false});
  canvasWrap.addEventListener("mousedown",function(event){if(event.button!==0)return;event.preventDefault();const p=pointerPosition(event);if(!p)return;if(tool==="point"){selectedId=engine.add({type:"point",x:p.x,y:p.y}).id;render();setStatus("Punt toegevoegd.");return;}if(tool==="text"){const text=global.prompt("Tekst voor de illustratie:","A");if(text!==null&&text.trim()){selectedId=engine.add({type:"text",x:p.x,y:p.y,text:text.trim()}).id;render();setStatus("Tekst toegevoegd.");}return;}if(tool==="line"||tool==="circle"){drag={start:p};engine.renderer.preview={type:tool,start:p,end:p};crosshair.hidden=false;updateCrosshair(event);render();return;}const hit=engine.selectAt(p.x,p.y,0.18);if(hit){selectedId=hit.object.id;drag={start:p,objectId:selectedId};setStatus("Object geselecteerd.");}else{selectedId=null;setStatus("Geen object geselecteerd.");}render();});
  function updateCrosshair(event){const r=canvasWrap.getBoundingClientRect();crosshair.style.left=event.clientX-r.left+"px";crosshair.style.top=event.clientY-r.top+"px";}
  global.addEventListener("mousemove",function(event){if(!drag)return;const p=pointerPosition(event);if(!p)return;if(tool==="line"||tool==="circle"){engine.renderer.preview.end=p;updateCrosshair(event);render();return;}if(tool==="select"&&drag.objectId){engine.move(drag.objectId,p.x,p.y);render();}});
  global.addEventListener("mouseup",function(event){if(!drag)return;const end=pointerPosition(event),current=drag;drag=null;crosshair.hidden=true;if(!end){engine.renderer.preview=null;render();return;}if(tool==="line")finishLine(current.start,end);if(tool==="circle")finishCircle(current.start,end);});
  document.getElementById("toolGrid").addEventListener("click",e=>{const b=e.target.closest("[data-tool]");if(b)activateTool(b.dataset.tool);});
  axesBtn.addEventListener("click",()=>{engine.renderer.showAxes=!engine.renderer.showAxes;render();setStatus(engine.renderer.showAxes?"Assenstelsel getoond.":"Assenstelsel verborgen.");});
  gridBtn.addEventListener("click",()=>{engine.renderer.showGrid=!engine.renderer.showGrid;render();setStatus(engine.renderer.showGrid?"Raster getoond.":"Raster verborgen.");});
  document.getElementById("applyBoundsBtn").addEventListener("click",applyBounds);
  [xMinInput,xMaxInput,yMinInput,yMaxInput].forEach(i=>i.addEventListener("keydown",e=>{if(e.key==="Enter")applyBounds();}));
  titleInput.addEventListener("input",render);descriptionInput.addEventListener("input",render);
  document.getElementById("newBtn").addEventListener("click",function(){if(!global.confirm("Een nieuwe illustratie starten? Niet-opgeslagen wijzigingen gaan verloren."))return;const r=engine.renderer;engine=new MI.Engine(null,{width:r.width,height:r.height,bounds:{xMin:-5,yMin:-3,xMax:5,yMax:3},background:r.background,padding:r.padding,showAxes:r.showAxes,showGrid:r.showGrid,axisStep:r.axisStep});selectedId=null;titleInput.value="";descriptionInput.value="";render();setStatus("Nieuwe illustratie gestart.");});
  document.getElementById("saveBtn").addEventListener("click",()=>{updateMeta();localStorage.setItem(STORAGE_KEY,engine.toJSONString(true));setStatus("Concept opgeslagen in deze browser.");});
  document.getElementById("loadBtn").addEventListener("click",()=>document.getElementById("fileInput").click());
  document.getElementById("fileInput").addEventListener("change",function(event){const file=event.target.files&&event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=function(){try{engine.load(JSON.parse(reader.result));titleInput.value=engine.model.meta.title||"";descriptionInput.value=engine.model.meta.description||"";selectedId=null;render();setStatus("Illustratie geladen.");}catch(error){global.alert("JSON kon niet worden geladen: "+error.message);}event.target.value="";};reader.readAsText(file);});
  function download(name,content,type){const blob=new Blob([content],{type:type}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
  document.getElementById("exportJsonBtn").addEventListener("click",()=>{updateMeta();download("illustratie.json",engine.toJSONString(true),"application/json;charset=utf-8");setStatus("JSON geëxporteerd.");});
  document.getElementById("exportSvgBtn").addEventListener("click",()=>{updateMeta();download("illustratie.svg",engine.renderSVG(),"image/svg+xml;charset=utf-8");setStatus("SVG geëxporteerd.");});
  global.addEventListener("keydown",function(event){if((event.key==="Delete"||event.key==="Backspace")&&selectedId&&document.activeElement.tagName!=="INPUT"&&document.activeElement.tagName!=="TEXTAREA"){engine.remove(selectedId);selectedId=null;render();setStatus("Object verwijderd.");}if(event.key==="Escape"){drag=null;engine.renderer.preview=null;crosshair.hidden=true;activateTool("select");render();}});
  try{const draft=localStorage.getItem(STORAGE_KEY);if(draft){engine.load(JSON.parse(draft));titleInput.value=engine.model.meta.title||"";descriptionInput.value=engine.model.meta.description||"";setStatus("Opgeslagen concept geladen.");}}catch(error){localStorage.removeItem(STORAGE_KEY);setStatus("Nieuw werkvlak.");}
  render();
})(window);
